
import './globals.css';


import { Inter } from 'next/font/google'
import Footer from './sections/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tinh te',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <head>
        <meta name='metadata'/>
      </head>
      <body className={inter.className}>{children}
      <Footer/>
      </body>
      
    </html>
  )
}
